### ISSUE TITLE
"No website, description, or topics provided"

### ISSUE THREAD

**Issue by vielmetti** [jmarhee/github-repo-practices#1]
Github notes that this repo doesn't have a website, description, or topics. Add that to the checklist.

**Comment by vielmetti** [comment]
Hm, this should be a testable condition too....by pulling from https://developer.github.com/v3/repos/ and inspecting the JSON you get back for a few bits of info.

**Comment by jmarhee** [comment]
Opened https://github.com/jmarhee/github-repo-practices/pull/3 with tests for topics, description, and homepage presence
